[package]
edition      = "2024"
name         = "wx_esp32s3"
rust-version = "1.95"
version      = "0.1.0"

[[bin]]
name = "wx_esp32s3"
path = "./src/bin/main.rs"

[dependencies]
time = { version = "0.3", default-features = false }
pcf85063a = "0.1.1"
esp-hal = { version = "~1.2.2", features = ["defmt", "esp32s3", "unstable"] }
embedded-can = "0.4"

esp-rtos = { version = "0.4.0", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32s3",
] }

picoserve = { version = "0.18", features = ["embassy"] }
heapless = "0.8"
embassy-futures = "0.1"
defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.6.0", features = ["defmt", "esp32s3"] }
embassy-sync = { version = "0.7", features = ["defmt"] }
embassy-net = { version = "0.9.1", features = [
  "defmt",
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = { version = "0.7.1", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
esp-alloc = { version = "0.11.0", features = ["defmt", "esp32s3"] }
esp-println = { version = "0.18.0", features = ["defmt-espflash", "esp32s3"] }
bt-hci = "0.9.0"
embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
esp-radio = { version = "1.0.0-beta.1", features = [
  "ble",
  "coex",
  "defmt",
  "esp-alloc",
  "esp32s3",
  "unstable",
  "wifi",
] }
smoltcp = { version = "0.14.0", default-features = false, features = [
  "defmt",
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
trouble-host = { version = "0.7.0", features = ["gatt"] }

critical-section = "1.2.0"
static_cell      = "2.1.1"

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug         = 2
lto           = 'fat'
opt-level     = 's'

[profile.dev.package.esp-radio]
opt-level = 3
